import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Loader2, Sparkles, AlertCircle } from 'lucide-react';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { useToast } from '@/hooks/use-toast';

interface AIGenerateSection11Props {
  formData: any;
  language: 'fr' | 'en';
  onGenerated: (conclusion: {
    resume: string;
    diagnostic: string;
    dateConsolidation: string;
    soinsTraitements: string;
    atteintePermanente: string;
    limitationsFonctionnelles: string;
    evaluationLimitations: string;
  }) => void;
}

export function AIGenerateSection11({ formData, language, onGenerated }: AIGenerateSection11Props) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const { toast } = useToast();

  const handleGenerate = async () => {
    setIsGenerating(true);
    setError(null);

    try {
      const response = await fetch('/api/generate-section11', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: 'include',
        body: JSON.stringify({
          formData,
          language,
          selectedGender: (formData as any).selectedGender || null
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to generate conclusion');
      }

      const conclusion = await response.json();
      onGenerated(conclusion);
      
      toast({
        title: language === 'fr' ? "Conclusion générée" : "Conclusion generated",
        description: language === 'fr' 
          ? "La conclusion a été générée avec succès par l'IA" 
          : "The conclusion has been successfully generated by AI",
      });
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      setError(errorMessage);
      
      toast({
        title: language === 'fr' ? "Erreur" : "Error",
        description: errorMessage,
        variant: "destructive",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const hasRequiredData = () => {
    // Check if there's enough data to generate a meaningful conclusion
    return (
      formData.antecedentsMedicaux ||
      formData.antecedentsChirurgicaux ||
      formData.medicationActuelle ||
      formData.historiqueEvolution ||
      formData.appreciationEvolution ||
      formData.plaintesproblemes ||
      formData.impactAvq ||
      formData.observationGenerale
    );
  };

  if (!hasRequiredData()) {
    return (
      <Alert>
        <AlertCircle className="h-4 w-4" />
        <AlertDescription>
          {language === 'fr'
            ? "Veuillez remplir au moins une section (5-9) avant de générer la conclusion."
            : "Please complete at least one section (5-9) before generating the conclusion."}
        </AlertDescription>
      </Alert>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 p-4 bg-blue-50 dark:bg-blue-950 rounded-lg border border-blue-200 dark:border-blue-800">
        <Sparkles className="h-5 w-5 text-blue-600 dark:text-blue-400" />
        <div>
          <h3 className="font-medium text-blue-900 dark:text-blue-100">
            {language === 'fr' ? "Génération automatique" : "Automatic generation"}
          </h3>
          <p className="text-sm text-blue-700 dark:text-blue-300">
            {language === 'fr'
              ? "L'IA peut générer une conclusion médicale professionnelle basée sur les sections 5-9."
              : "AI can generate a professional medical conclusion based on sections 5-9."}
          </p>
        </div>
      </div>

      {error && (
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      <Button
        onClick={handleGenerate}
        disabled={isGenerating}
        className="w-full"
        size="lg"
      >
        {isGenerating ? (
          <>
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            {language === 'fr' ? "Génération en cours..." : "Generating..."}
          </>
        ) : (
          <>
            <Sparkles className="mr-2 h-4 w-4" />
            {language === 'fr' ? "Générer la conclusion avec l'IA" : "Generate conclusion with AI"}
          </>
        )}
      </Button>

      <p className="text-xs text-muted-foreground text-center">
        {language === 'fr'
          ? "La conclusion générée peut être modifiée manuellement après génération."
          : "The generated conclusion can be manually edited after generation."}
      </p>
    </div>
  );
}